### PR TITLE
autodetection of sitePAth, no need to configure it

### PR DESCRIPTION
**Pull request by mckaygerhard**
* featured autoconfiguration of `sitePath` root 
* it also supports SEO

### CODE REVIEW

**Comment by arnaudsm** [comment]
This code breaks the tests. Users can open the website from another page than the homepage.

Eg: when opening `localhost:3000/docs/` with browser routing, the code sets `sitePath` to `/docs/`, which is obviously incorrect.

Which problem are you trying to solve ? Isn't the default `sitePath` enough ?

**Comment by mckaygerhard** [comment]
oh no! you have right.. i noted that and i am making some code refactoring as the picture shows.. wait for me

Screenshot at 2023-07-18 09-47-44

**Comment by mckaygerhard** [comment]
the idea is that at first try .. launch a user alert to demand configuration, after that we can just tell user that must configure constants

**Comment by mckaygerhard** [comment]
i will close this cos after many test and try, concluded that must be set manually the root site path due security issues..

**Pull request closed without merging**
